server:
  port: 8080
  shutdown: graceful
  
logging:
  level[net.talaatharb.tasks]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:../db/tasks;AUTO_SERVER=TRUE;
    username: sa
    password: